### ISSUE TITLE
Action_GIST compiling warning

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cpptraj#695]
hi,

I am not sure if this is helpful but I still report here while I am playing around with cpptraj:
```
Action_GIST.cpp: In function ‘void _ZN11Action_GIST13NonbondEnergyERK5FrameRK8Topology.omp_fn.1(void*)’:
Action_GIST.cpp:507: warning: ‘eij_v1’ may be used uninitialized in this function
Action_GIST.cpp:507: note: ‘eij_v1’ was declared here
Action_GIST.cpp:508: warning: ‘eij_v2’ may be used uninitialized in this function
Action_GIST.cpp:508: note: ‘eij_v2’ was declared here
Action_GIST.cpp:509: warning: ‘eij_en’ may be used uninitialized in this function
Action_GIST.cpp:509: note: ‘eij_en’ was declared here
```

**Comment by drroe** [comment]
These are spurious warnings since they are only assigned/used when `doEij_` is true. Doesn't really cost anything for me to initialize them though.

**Comment by drroe** [comment]
@hainm should be addressed by #698 - let me know if not.

**Comment by hainm** [comment]
I still see the warning

I also see the warning from Action_XtalSymm too.
```
Action_XtalSymm.cpp: In member function ‘bool Action_XtalSymm::OriginsAlign(Action_XtalSymm::XtalDock*, const std::vector<int, std::allocator<int> >&, int) const’:
Action_XtalSymm.cpp:607: warning: ‘origx’ may be used uninitialized in this function
Action_XtalSymm.cpp:607: warning: ‘origy’ may be used uninitialized in this function
Action_XtalSymm.cpp:607: warning: ‘origz’ may be used uninitialized in this function
```

**Comment by drroe** [comment]
Addressed by #695 and #898
